# Generated by Django 3.0.7 on 2020-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
